[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=0; includeSubDomains"
    Content-Security-Policy = "upgrade-insecure-requests"
[[redirects]]
  from = "/api/*"
  to = "http://109.73.206.144:6969/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FORCE_HTTPS = "false" 